# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Answer:	4613732

      arr = []
      arr << 1
      y = 3
      x = 2
    while x < 4000000
      arr << x
      arr << y if y < 4000000
      x += y
      y += x
    end


even = 0

arr.each do |x|
  even += x if x % 2 == 0
end

print even